#GLOBAL CONFIG
SETTINGS_STR: str = "setings"
SYMBOL_STR: str = "symbol"
INTERVAL_STR: str = "interval"
LIMIT_STR: str = "limit"
BUY_STR: str = "buy"
MIN_DROP_STR: str = "min_drop"
MAXIMUM_DROP_STR: str = "maximum_drop"
BUY_PERCENTAGE_STR: str = "buy_percentage"
REFILL_PERCENTAGE_STR: str = "refill_percentage"
SELL_STR: str = "sell"
MIN_RISE_STR: str = "min_rise"
MAXIMUM_RISE_STR: str = "maximum_rise"
SELL_PERCENTAGE_STR: str = "refill_percentage"
CONFIG_STR: str = "config"
CONFIG_PY_STR: str = "config.py"
LOGS_STR: str = "logs"
LOGS_TXT_STR: str = f"{LOGS_STR}.txt"
STRATEGIES_STR: str ="strategies"
REDIRECT_TO_STRATEGIES_STR: str = "redirect_to_strategies"
MEAN_REVERSION_STR: str = "mean_reversion"
#QUERY
TOTAL_STR: str = "total"
USDT_STR: str = "USDT"
